markdown:         kramdown
syntax-css:       gruvbox
title:            tho's light
tagline:          short and sweet
email:            your-email@example.com
linkedin:         https://www.linkedin.com
github:           https://github.com
baseurl: /
url:  
paginate: 5

plugins:
  - jekyll-paginate
