markdown:           kramdown
                    
syntax-rouge-theme: tomorrow-night
                    # base16.dark
                    # base16.monokai.dark
                    # base16.solarized.dark
                    # gruvbox.dark
                    # molokai
                    # monokai
                    # thankful_eyes
                    # tulip


title:              tho's light
tagline:            short and sweet
email:              your-email@example.com
linkedin:           https://www.linkedin.com
github:             https://github.com
baseurl:            /
url:                https://inpursuitofhisownhat.github.io/thos-light/
paginate:           5

plugins:
                    - jekyll-paginate
